title: Home
views:
  - path: default_view
    title: Home
    panel: true
    cards:
      - type: custom:layout-card
        layout: vertical
        min_columns: 1
        max_columns: 3
        cards:
          - type: entities
            entities:
              - type: divider
              - entity: sensor.upstairs_average
                icon: mdi:thermometer
              - sensor.outside_front_sensor_temperature
              - sensor.electric_meter_power
              - sensor.daily_energy
              - sensor.current_solar_watts
          - type: grid
            columns: 3
            cards:
              - type: vertical-stack
                cards:
                  - type: sensor
                    entity: sensor.living_room_sensor_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.kitchen_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_a4_c1_38_a5_fd_de_bathroom_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.rack_sensor_temperature
                    graph: line
                    hours_to_show: 6
              - type: vertical-stack
                cards:
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_a4_c1_38_79_01_ce_ensuite_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.toilet_sensor_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_atc_58447f_office_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.spare_bedroom_sensor_temperature
                    graph: line
                    hours_to_show: 6
              - type: vertical-stack
                cards:
                  - type: sensor
                    entity: sensor.hall_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.mqtt_xiaomi_loft_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.master_bedroom_sensor_temperature
                    graph: line
                    hours_to_show: 6
                  - type: sensor
                    entity: sensor.outside_front_sensor_temperature
                    graph: line
                    hours_to_show: 6
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
            filter:
              include:
                - entity_id: "*_humidity"
              exclude:
                - state: unknown
                - state: '< 65'
          - break
          - type: glance
            entities:
              - entity: binary_sensor.mqtt_backdoor
              - entity: binary_sensor.mqtt_frontdoor
              - entity: binary_sensor.mqtt_office_window
            state_color: true
          - type: custom:auto-entities
            show_empty: false
            card:
              type: glance
              state_color: true
            filter:
              include:
                - domain: person
                - entity_id: "alarm_control_panel.automated_alarm_panel"
                - entity_id: "switch.mqtt_guest_mode_switch"
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
            sort:
              numeric: true
            filter:
              include:
                - domain: sensor
                  attributes:
                    device_class: battery
              exclude:
                - state: unknown
                - state: unavailable
                - state: Not Charging
                - state: Full
                - state: '> 10'
          - type: picture-entity
            entity: camera.garden_left
            camera_view: live
          - break
          - type: plant-status
            entity: plant.kitchen_plant
          - type: 'custom:vacuum-card'
            entity: vacuum.jeff
            compact_view: true
            stats:
              cleaning:
                - attribute: cleaned_area
                  unit: m2
                  subtitle: Cleaning area
                - attribute: cleaning_time
                  unit: minutes
                  subtitle: Cleaning time
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: 'Bin Schedule'
            filter:
              include:
                - domain: input_datetime
  - path: debug
    title: Debug
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: light
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: binary_sensor
          exclude:
            - entity_id: "*_update_available"
            - entity_id: "*_led_indication"
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: sensor
          exclude:
            - entity_id: "*_update_state"
            - entity_id: "*_linkquality"
            - entity_id: "*_sensor_illuminance"
            - entity_id: "*_illuminance_lux"
            - entity_id: "*_motion_sensitivity"
            - entity_id: "*_occupancy_timeout"
            - entity_id: "*_battery"
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: switch
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: timer
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: camera
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Batteries
        sort:
          numeric: true
        filter:
          include:
            - domain: sensor
              attributes:
                device_class: battery
  - path: switches
    title: Switches
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: switch
  - path: shed
    title: Shed
    cards:
      - type: history-graph
        title: 'Temperature'
        hours_to_show: 12
        entities:
          - sensor.shed_battery_temp
          - sensor.shed_controller_temp
          - sensor.shed_pi_temp
      - type: gauge
        name: 'Battery'
        entity: sensor.shed_battery_voltage
        unit: 'v'
        max: 14.5
        min: 10
      - type: gauge
        name: 'Charge'
        entity: sensor.shed_charge_voltage
        unit: 'v'
        max: 23
        min: 12
      - type: gauge
        name: 'Charge'
        entity: sensor.shed_charge_current
        unit: 'v'
        max: 6
        min: 0
      - type: gauge
        name: 'Charge Watts'
        entity: sensor.shed_charge_power
        unit: 'W'
        max: 100
        min: 0
      - type: sensor
        entity: sensor.shed_battery_voltage
        hours_to_show: 24
        graph: line
  - path: lights
    title: Lights
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: light
  - path: recorder
    title: Recorder
    cards:
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - entity_id: "states_*"
            - entity_id: "*_states_*"
            - entity_id: "*_entity_*"
