title: Energy
views:
  - title: Energy
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            name: 'Grid Export'
            entity: sensor.grid_export_power
            unit: 'W'
            max: 4000
            min: 0
          - type: gauge
            name: 'Grid Usage'
            entity: sensor.grid_energy_power
            unit: 'W'
            needle: true
            max: 6000
            min: 0
            severity:
              green: 0
              yellow: 1000
              red: 2000
      - type: horizontal-stack
        cards:
          - type: gauge
            name: 'Solar Generation'
            entity: sensor.solar_generating_power
            unit: 'W'
            max: 4800
            min: 0
            severity:
              green: 1000
              yellow: 600
              red: 0
          - type: gauge
            name: 'Power Usage'
            entity: sensor.power_usage
            unit: 'W'
            max: 6000
            min: 0
            severity:
              green: 0
              yellow: 1000
              red: 3000
      - type: energy-usage-graph
      - type: energy-distribution
        link_dashboard: false
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - entity_id: "sensor.energy_*"

