- platform: min_max
  type: mean
  name: 'Living Room Temperature'
  entity_ids:
    - sensor.mqtt_xiaomi_atc_34ef8f_living_room_temperature
    - sensor.mqtt_xiaomi_atc_15e359_living_room_temperature
- platform: min_max
  type: mean
  name: 'Hall Temperature'
  entity_ids:
    - sensor.hall_sensor_temperature
    - sensor.mqtt_xiaomi_hall_temperature
- platform: min_max
  type: mean
  name: 'Kitchen Temperature'
  entity_ids:
    - sensor.kitchen_front_sensor_temperature
    - sensor.kitchen_rear_sensor_temperature
- platform: min_max
  type: mean
  name: 'Upstairs Average'
  entity_ids:
    - sensor.master_bedroom_sensor_temperature
    - sensor.mqtt_xiaomi_atc_58447f_office_temperature
    - sensor.spare_bedroom_sensor_temperature
    - sensor.landing_sensor_temperature
- platform: statistics
  name: office_temperature_stat
  entity_id: sensor.mqtt_xiaomi_atc_58447f_office_temperature
  max_age: 300
  sampling_size: 3
