- alias: 'Turn on hall & landing light when there is movement day mode'
  id: 'turn_on_hall_and_landing_when_movement-day'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_or_landing_motion
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.hall_sensor_illuminance_lux
      above: '90'
  action:
    service: light.turn_on
    target:
      entity_id: light.hall_lights
    data:
      brightness: 254
      transition: 1

- alias: 'Turn on hall light when there is movement night mode'
  id: 'turn_on_hall_and_landing_when_movement-night'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_or_landing_motion
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.hall_sensor_illuminance_lux
      below: '91'
  action:
    service: light.turn_on
    target:
      # i.e. the downstairs one only (not the landing since they are near bedrooms)
      entity_id: light.hall_light
    data:
      brightness: 10

- alias: 'Turn off hall/landing light 3 minutes after last movement'
  id: 'turn_off_hall_and_landing_after_3_minutes_of_no_movement'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_or_landing_motion
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    target:
      entity_id: light.hall_lights
    data:
      transition: 10
