- alias: '[Kitchen] Turn on light when there is movement'
  id: 'kitchen_turn_on_light_when_there_is_movement'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  action:
    - service: light.turn_on
      target:
        entity_id: light.kitchen_rear_light
      data:
        brightness: 254

- alias: '[Kitchen] Turn off light when there is no movement'
  id: 'kitchen_turn_off_light_when_there_is_no_movement'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    target:
      entity_id: light.kitchen_rear_light
