- alias: '[Outside] Turn on light when there is movement'
  id: 'outside_light_on_after_five'
  trigger:
    platform: state
    entity_id: binary_sensor.outside_sensor_occupancy
    to: 'on'
  condition:
    - condition: time
      after: '17:01:00'
  action:
    service: light.turn_on
    target:
      entity_id: light.outside_light
    data:
      brightness: 254

- alias: '[Outside] Start/Restart timer if occupancy OR light is switched on'
  trigger:
    - platform: state
      entity_id: binary_sensor.outside_sensor_occupancy
      to: 'on'
    - platform: state
      entity_id: light.outside_light
      to: 'on'
      from: 'off'
  action:
    service: timer.start
    target:
      entity_id: timer.outside

- alias: "[Outside] Turn off outside light after timer finishes"
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.outside
  action:
    service: light.turn_off
    target:
      entity_id: light.outside_light
